services:
  swampninjas:
    build:
      context: ..
      dockerfile: infra/backend.Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port ${UVICORN_PORT:-8000} --reload
    container_name: swampninjas
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_PUBLIC_DIR=/app/frontend/public
    env_file:
      - .env
    volumes:
      - ../backend:/app/backend
      - ../frontend/public:/app/frontend/public
    ports:
      - "${UVICORN_PORT:-8000}:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s

volumes:
  pg_data:
